# Use the official Bun image for building the application
FROM oven/bun:latest AS builder

# Set the working directory in the container
WORKDIR /projects/web

# Copy package files
COPY package.json ./
COPY bun.lockb ./

# Install dependencies
RUN bun i

# Copy all other files
COPY . ./

# Use a smaller image for running the application
FROM oven/bun:latest

# Set the working directory in the container
WORKDIR /projects/web

# Copy only the necessary files from the builder image to the final image
COPY --from=builder /projects/web .

# Expose the port the application will run on
EXPOSE 5173

# Start the application
CMD ["bun", "run", "dev"]